# Generated by Django 3.0.2 on 2020-02-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40, verbose_name='사용자 이름')),
                ('user_password', models.CharField(max_length=40, verbose_name='비밀번호')),
                ('created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('user_email', models.EmailField(max_length=128, verbose_name='이메일')),
            ],
            options={
                'verbose_name': '커뮤니티 사용자',
                'verbose_name_plural': '커뮤니티 사용자',
                'db_table': 'tb_community_user',
            },
        ),
    ]
